### ISSUE TITLE
How should I set the width of this alertView?

### ISSUE THREAD

**Issue by CaledoniaProject** [regexident/DLAlertView#34]
It seems like I had to modify the class to accomplish it.

If otherwise, can you provide some sample code?

**Comment by CaledoniaProject** [comment]
Anyway, I'm fixing this issue with 

`-(void)willPresentAlertView:(UIAlertView *)alertView`

Which looks quiet dumb ....

**Comment by regexident** [comment]
The width and height get calculated automatically and depend on the alert's theme parameters. As such there is no reliable way to provide a custom size (not even through `willPresentAlertView:`).

**Comment by CaledoniaProject** [comment]
Hi @regexident  I mean, I'm just trying to increase the left & right margin to the screen ... so I should do it through themes

**Comment by regexident** [comment]
The alert's size is calculated the other way around, that is based on its contents, not the screen around it.

**Comment by CaledoniaProject** [comment]
Thanks @regexident I'll check on the size of the contentView then
