### ISSUE TITLE
`clickedButtonAtIndex` be called twice in `dismissWithBackdropTap`

### ISSUE THREAD

**Issue by Whirlwind** [regexident/DLAlertView#37]
There is not the `alertViewCancel`, the `alertView:clickedButtonAtIndex:` will be called in the `dismissWithBackdropTap` at first. Then the second called in the `- (void)dismissWithClickedButtonIndex:(NSInteger)buttonIndex animated:(BOOL)animated`.

**Comment by regexident** [comment]
Should be fixed in commit f70e708.
