### ISSUE TITLE
How can I handle frame of DLAlert with custom textView as a contentView?

### ISSUE THREAD

**Issue by bizibizi** [regexident/DLAlertView#40]
please help to achieve this 

I have tableView as a contentView and in the bottom row I have textView

**Comment by regexident** [comment]
What is it exactly that you want to accomplish?
And more importantly: what have you tried so far?

**Comment by bizibizi** [comment]
I need to have 2 lines textView, I made this with handling keyboard notifications in my VC, will be very handy if you add this capability in your library. Thanks

**Comment by regexident** [comment]
I'm hesitant to adding any further additional features to the library as it's already quite crowded and most those feature requests are of little use to the general audience and would thus be merely adding bloat.

If the current API does not fit your bill, then nobody will stop you from implementing the wanted view widgets (multi-line textviews, …you name it) and injecting it via `contentView`. That's what `contentView` is for after all.
