### ISSUE TITLE
Is not possible display content view in the top when title and message is visible

### ISSUE THREAD

**Issue by avshiyanov** [regexident/DLAlertView#42]
Please add ability display content in the top. Now it's always in the bottom. I think problem is here:

// Layout title:
	if (self.title) {
		[self layoutTitleLabelWithTheme:theme inAlertWithSize:alertSize atVerticalOffset:&offset];
	}
	
	// Layout message:
	if (self.message) {
		[self layoutMessageLabelWithTheme:theme inAlertWithSize:alertSize atVerticalOffset:&offset];
	}
	
	self.messageLabel.hidden = self.message == nil;
	
	// Layout content view:
	if (self.contentView) {

**Comment by regexident** [comment]
> Please add ability display content in the top.

As I **already told you** (and explained the reasoning for) in issue #41 there will be **no new features** for `DLAlertView`.
It is in **feature-freeze** / **maintenance-only** mode and adding further issues **won't change** that.

In the meanwhile feel free to **fork the project** and change/add whatever floats your boat.

**Comment by ayoze** [comment]
@avshiyanov check my fork if you want, I've implemented this.

@regexident do you want me to make a pull request for that functionality?
